pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'javac -cp .:junit.jar HelloWorldTest.java'
                sh 'java  -cp .:junit.jar:hamcrest.jar org.junit.runner.JUnitCore HelloWorldTest'
            }
        }
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
